hyper_event:
    resource: "@HyperEventBundle/Resources/config/routing.yml"
    prefix:   /

#hg_event:
#    resource: "@HGEventBundle/Resources/config/routing.yml"
#    prefix:   /

#hypergrowth_event_store:
#    resource: "@HypergrowthEventStoreBundle/Resources/config/routing.yml"
#    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
